name: Backend CI/CD (EC2)

on:
  push:
    branches:
      - main

env:
  SONAR_PROJECT_KEY: P-r-a-n-a-v-N-a-i-r_projecthub-node
  SONAR_ORG: p-r-a-n-a-v-n-a-i-r

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: sonarqube
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}        # ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_IMAGE }}         # ghcr.io/<user>/projecthub-backend
        run: |
          echo "Building image $IMAGE_NAME:${{ github.sha }}"
          docker buildx build --tag $IMAGE_NAME:${{ github.sha }} --tag $IMAGE_NAME:latest --push .

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 via SSH
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_IMAGE }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REG_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REG_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES: ${{ secrets.JWT_EXPIRES }}
          BCRYPT_ROUNDS: ${{ secrets.BCRYPT_ROUNDS }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
            echo '$REG_PASSWORD' | docker login $REGISTRY -u '$REG_USERNAME' --password-stdin &&
            docker pull $IMAGE_NAME:latest &&
            docker ps -q --filter 'name=projecthub-backend' | xargs -r docker stop &&
            docker ps -aq --filter 'name=projecthub-backend' | xargs -r docker rm &&
            docker run -d --name projecthub-backend -p 80:5000 \
              -e NODE_ENV=production \
              -e MONGO_URI='$MONGO_URI' \
              -e JWT_SECRET='$JWT_SECRET' \
              -e JWT_EXPIRES='$JWT_EXPIRES' \
              -e BCRYPT_ROUNDS='$BCRYPT_ROUNDS' \
              -e BREVO_API_KEY='$BREVO_API_KEY' \
              -e GOOGLE_CLIENT_ID='$GOOGLE_CLIENT_ID' \
              $IMAGE_NAME:latest
          "
